### ISSUE TITLE
Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1809a31d8)

### ISSUE THREAD

**Issue by marcosvsSampaio** [Catapush/catapush-flutter-sdk#1]
## Error Report
I'm trying to implement the catapush-flutter-sdk in my project. I followed all the step guide to implement the sdk for iOS and the example project of how to use the catapush-flutter-sdk. But I have the following error when I run the application in the IOS:

Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1809a31d8)

![image](https://user-images.githubusercontent.com/54193994/143305258-5825ac1b-d1d6-4078-bf9c-4bd34f6777ff.png)

![image](https://user-images.githubusercontent.com/54193994/143305333-1508f0b8-15f8-48e2-8363-15fc6ffb4f0e.png)

![image](https://user-images.githubusercontent.com/54193994/143305388-739652f2-d35b-464d-be03-f4336abc48f4.png)

![image](https://user-images.githubusercontent.com/54193994/143305452-a35f1258-e9fd-4fc9-a962-11c91068fe26.png)

### Flutter doctor

Run `flutter doctor -v` and paste the output below:

```
marcosvinicius@MacBook-Pro-de-admin ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.0, on macOS 12.0.1 21A559 darwin-x64, locale pt-BR)
    • Flutter version 2.0.0 at /Users/marcosvinicius/Documents/Delvelopment/flutterV2
    • Framework revision 60bd88df91 (9 months ago), 2021-03-03 09:13:17 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/marcosvinicius/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by maxcorrads** [comment]
Hi,
this error happens when there is no AppGroup specified in the Info.plist, could you please check that you have added the group information in both the Info.plist (App and Extension)?

```
<key>Catapush</key>
<dict>
    <key>AppGroup</key>
    <string>group.example.group</string>
</dict>
```

I also suggest upgrading flutter to the latest version.

Thank you

**Comment by marcosvsSampaio** [comment]
I forgot to specify the AppGroup in the Runner Info.plist. Now it's working.
Thanks @maxcorrads.
